Vagrant.configure("2") do |config|
  config.vm.box = "centos64-x64-vbox43-1383512148"
  config.vm.box_url = "http://box.puphpet.com/centos64-x64-vbox43.box"
  config.vm.hostname = "vagrant.movies"
  config.vm.network "private_network", ip: "192.168.56.102"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder ".", "/var/www/movies"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../_docs/vagrant/manifests"
    puppet.manifest_file  = "default.pp"
    puppet.options = "--verbose --debug"
  end  



  # If a 'Vagrantfile.local' file exists, import any configuration settings
  # defined there into here. Vagrantfile.local is ignored in version control,
  # so this can be used to add configuration specific to this computer.
  if File.exist? "Vagrantfile.local"
    instance_eval File.read("Vagrantfile.local"), "Vagrantfile.local"
  end  

end